function ps_simwithplotting(simcfg,varargin)
%
%  
% New version for calculating simulation and residuals of Phase...
%
% 
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
postfix = 'Nepal1505';
% 
outsimfile = psokinv_simglobal(simcfg,...
             'ispara',0,...
             'simulation','MO',...
             'outpixelsize',0.001);
siminfo    = sim_getsimcfg(simcfg);  
%
for ni = 3:numel(siminfo.unwf)
    sar_phs2resfromenu(siminfo.unwf{ni},...
        outsimfile{1},...
        outsimfile{2},...
        outsimfile{3},...
        'postfix',      postfix,...
        'gmt_minwrap', -10,...
        'gmt_maxwrap',  10,...
        'ininc',        siminfo.incf{ni},...
        'inazi',        siminfo.azif{ni});
end